CREATE TABLE `care_plan_tasks` (
  `task_id` bigint NOT NULL AUTO_INCREMENT COMMENT '护理任务ID',
  `care_plan_id` bigint NOT NULL COMMENT '护理计划ID',
  `elder_id` bigint NOT NULL COMMENT '老人ID',
  `assigned_nurse_id` bigint DEFAULT NULL COMMENT '分配的护士ID',
  `task_type` varchar(64) DEFAULT NULL COMMENT '任务类型',
  `task_title` varchar(128) NOT NULL COMMENT '任务标题',
  `task_content` text COMMENT '任务内容',
  `frequency_desc` varchar(128) DEFAULT NULL COMMENT '执行频率描述',
  `suggested_time` varchar(128) DEFAULT NULL COMMENT '建议执行时间',
  `scheduled_date` date DEFAULT NULL COMMENT '计划执行日期',
  `scheduled_time` time DEFAULT NULL COMMENT '计划执行时间',
  `scheduled_at` datetime DEFAULT NULL COMMENT '计划执行日期时间',
  `task_source` varchar(32) DEFAULT 'care_plan' COMMENT '任务来源：care_plan/手动创建等',
  `task_group_key` varchar(64) DEFAULT NULL COMMENT '同一护理项目展开后的分组标识',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending待执行/completed已完成/cancelled已取消',
  `execution_result` text COMMENT '执行结果',
  `executed_at` datetime DEFAULT NULL COMMENT '执行时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`task_id`),
  KEY `idx_task_plan` (`care_plan_id`),
  KEY `idx_task_elder` (`elder_id`),
  KEY `idx_task_plan_schedule` (`care_plan_id`, `scheduled_at`),
  KEY `idx_task_nurse_status` (`assigned_nurse_id`, `status`),
  CONSTRAINT `fk_care_plan_tasks_plan` FOREIGN KEY (`care_plan_id`) REFERENCES `care_plans` (`care_plan_id`),
  CONSTRAINT `fk_care_plan_tasks_elder` FOREIGN KEY (`elder_id`) REFERENCES `users` (`user_id`),
  CONSTRAINT `fk_care_plan_tasks_nurse` FOREIGN KEY (`assigned_nurse_id`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='护理计划任务明细表';
